eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 9101
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet : debug
spring:
  #zipkin:
  # base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest